# Sentiment Analysis Project
In this notebook, I'll document my process of creating a machine learning model that analyzes Twitter messages and predicts their sentiment.

In [14]:
import contractions
import nltk
import numpy as np
import pandas as pd
import tensorflow as tf
import torch

from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from huggingface_hub import hf_hub_download
from gensim.models import KeyedVectors
from nltk.tokenize import TweetTokenizer
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Embedding, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tqdm import tqdm

In [2]:
data = pd.read_csv('Data/sentiment_data.csv')
data = data.dropna()
data.head()

   Unnamed: 0                                            Comment  Sentiment
0           0  lets forget apple pay required brand new iphon...          1
1           1  nz retailers don’t even contactless credit car...          0
2           2  forever acknowledge channel help lessons ideas...          2
3           3  whenever go place doesn’t take apple pay doesn...          0
4           4  apple pay convenient secure easy use used kore...          2

In [3]:
repo_id = "fse/glove-twitter-200"   # repo name on Hugging Face
file1 = "glove-twitter-200.model"
file2 = "glove-twitter-200.model.vectors.npy"
    
# Download both
model_file = hf_hub_download(repo_id=repo_id, filename=file1)
vectors_file = hf_hub_download(repo_id=repo_id, filename=file2)
    
print("Downloaded model:", model_file)
print("Downloaded vectors:", vectors_file)

glove_model = KeyedVectors.load(model_file)

Downloaded model: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model
Downloaded vectors: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model.vectors.npy

In [4]:
twtk = TweetTokenizer()

def make_token(sen):
    sen = contractions.fix(sen)
    return twtk.tokenize(sen)

data['Tokens'] = [make_token(sentence) for sentence in tqdm(data['Comment'])]
data.head()

100%|████████████████████████████████████████████████████████████████████████| 240928/240928 [00:15<00:00, 15220.71it/s]

,Unnamed: 0,Comment,Sentiment,Tokens
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us..."

In [5]:
#making dictionaries so that each word maps to it's vector

def make_token_vocab(sequences):
    token_vocab = set()  
    for seq in tqdm(sequences):
        for token in seq:
            if token in token_vocab:
                continue
            if token not in glove_model:
                continue
            token_vocab.add(token)
    return list(token_vocab)  
   
def make_token_indexes():
    indexes = []
    for index, token in tqdm(enumerate(token_vocab)):
        indexes.append(index + 1)
    return indexes

def make_vector_vocab():
    vector_vocab = []  
    for token in tqdm(token_vocab):
        vector_vocab.append(glove_model[token])
    return vector_vocab

token_vocab = make_token_vocab(data['Tokens'])
token_indexes = make_token_indexes()
vector_vocab = make_vector_vocab()

100%|███████████████████████████████████████████████████████████████████████| 240928/240928 [00:00<00:00, 419643.94it/s]
62681it [00:00, 3046280.77it/s]
100%|█████████████████████████████████████████████████████████████████████████| 62681/62681 [00:00<00:00, 746710.05it/s]

In [6]:
padding_token = '<PAD>'
padding_index = 0
padding_vector = np.zeros_like(vector_vocab[0])

token_vocab = [padding_token] + token_vocab
token_indexes = [padding_index] + token_indexes
vector_vocab = [padding_vector] + vector_vocab

token_index_dict = dict(zip(token_vocab, token_indexes))
token_vector_dict = dict(zip(token_vocab, vector_vocab))

In [7]:
#truncating message lengths
max_length = 100

data['Length'] = [len(tokens) for tokens in data['Tokens']]
data = data[data['Length'] < max_length]

In [22]:
def make_indices(seq):
    sequence = []
    for token in seq:
        if token not in glove_model:
            continue
        sequence.append(token_index_dict[token])
    return sequence

data['Indices'] = [make_indices(seq) for seq in tqdm(data['Tokens'])]

X_padded = pad_sequences(
    data['Indices'].tolist(), 
    maxlen=max_length, 
    padding='post',  
    truncating='post' 
)

embedding_matrix = np.array(vector_vocab)
data.head()

100%|████████████████████████████████████████████████████████████████████████| 240680/240680 [00:03<00:00, 70582.93it/s]

,Unnamed: 0,Comment,Sentiment,Tokens,Length,Indices
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,...",35,"[524, 16805, 49256, 53746, 37456, 57052, 23128..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr...",20,"[35703, 54041, 32801, 44794, 48069, 40212, 541..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,...",16,"[62514, 14706, 16042, 3042, 48326, 1925, 3685,..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ...",58,"[32610, 58619, 61937, 53029, 44794, 1462, 5374..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us...",14,"[53746, 37456, 59596, 46194, 44086, 27981, 156..."

In [23]:
X = X_padded
y = data['Sentiment'].values

# Split into 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

# Convert labels to tf.int32
y_train = tf.cast(y_train, tf.int32)
y_test = tf.cast(y_test, tf.int32)

### cuDNN & Padding:
Apparently, I accidentally set use_cudnn to False. cuDNN is a library from NVIDIA that makes neural networks run much faster on NVIDIA GPUs. Thinking it would make training faster, I set it to true. Immediately, I got an error saying that cuDNN required right-padded sequences, meaning there can't be padding (zeros) in between real tokens. This confused me because my sequences are right-padded. 

Later, I realized that the problem wasn't the padding, but the way the mask_zero=True interacts with the sequences. After weeks of experimentation, I resolved the issue by disabling automatic masking. Supposedly, the padding mask can be weird with cuDNN if Batch sequences aren’t strictly rectangular. 

My fear was that padding might confuse the model by interpreting it as real words. However, the model uses the final hidden state from the LSTM for classification, not the output from every word. So, the model should only remember important tokens, not padding.

In [24]:
def make_model():
    model = keras.Sequential()
    model.add(layers.Embedding(
        input_dim = len(token_vocab),
        output_dim = 200,
        weights = [embedding_matrix],  
        trainable = False,             
        mask_zero = False
    ))
    model.add(layers.LSTM(32, use_cudnn = True))
    model.add(layers.Dense(3, activation = 'softmax'))

    return model

model = make_model()

model.compile(
    optimizer = keras.optimizers.Adam(learning_rate=0.0001),
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │    12,536,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,536,400 (47.82 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 12,536,400 (47.82 MB)

None

In [25]:
model_history = model.fit(
    X_train, y_train,
    batch_size = 256,
    epochs = 20,
    verbose = 1,
    validation_data = (X_test, y_test),
)

Epoch 1/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 32s 40ms/step - accuracy: 0.4537 - loss: 1.0252 - val_accuracy: 0.5373 - val_loss: 0.9588
Epoch 2/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 35s 46ms/step - accuracy: 0.5628 - loss: 0.9197 - val_accuracy: 0.5800 - val_loss: 0.8952
Epoch 3/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 34s 45ms/step - accuracy: 0.5947 - loss: 0.8752 - val_accuracy: 0.5988 - val_loss: 0.8687
Epoch 4/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 35s 47ms/step - accuracy: 0.6089 - loss: 0.8511 - val_accuracy: 0.6104 - val_loss: 0.8481
Epoch 5/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 34s 45ms/step - accuracy: 0.6191 - loss: 0.8327 - val_accuracy: 0.6179 - val_loss: 0.8340
Epoch 6/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 34s 46ms/step - accuracy: 0.6265 - loss: 0.8176 - val_accuracy: 0.6236 - val_loss: 0.8234
Epoch 7/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 35s 46ms/step - accuracy: 0.6327 - loss: 0.8055 - val_accuracy: 0.6286 - val_loss: 0.8145
Epoch 8/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 35s 46ms/step - accuracy: 0.6371 - loss: 0.7948 - val_accuracy: 0.6325 - val_loss: 0.8061
Epoch 9/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 35s 46ms/step - accuracy: 0.6414 - loss: 0.7839 - val_accuracy: 0.6330 - val_loss: 0.7979
Epoch 10/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 34s 45ms/step - accuracy: 0.6462 - loss: 0.7710 - val_accuracy: 0.6422 - val_loss: 0.7824
Epoch 11/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 35s 46ms/step - accuracy: 0.6557 - loss: 0.7561 - val_accuracy: 0.6517 - val_loss: 0.7726
Epoch 12/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 36s 47ms/step - accuracy: 0.6675 - loss: 0.7412 - val_accuracy: 0.6663 - val_loss: 0.7716
Epoch 13/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 36s 47ms/step - accuracy: 0.6932 - loss: 0.7272 - val_accuracy: 0.6977 - val_loss: 0.7442
Epoch 14/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 37s 50ms/step - accuracy: 0.7083 - loss: 0.7122 - val_accuracy: 0.6977 - val_loss: 0.7321
Epoch 15/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 36s 48ms/step - accuracy: 0.7185 - loss: 0.6953 - val_accuracy: 0.7117 - val_loss: 0.7123
Epoch 16/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 40s 53ms/step - accuracy: 0.7270 - loss: 0.6799 - val_accuracy: 0.7158 - val_loss: 0.7049
Epoch 17/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 38s 50ms/step - accuracy: 0.7328 - loss: 0.6683 - val_accuracy: 0.7259 - val_loss: 0.6911
Epoch 18/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 38s 51ms/step - accuracy: 0.7382 - loss: 0.6579 - val_accuracy: 0.7291 - val_loss: 0.6799
Epoch 19/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 43s 57ms/step - accuracy: 0.7423 - loss: 0.6489 - val_accuracy: 0.7320 - val_loss: 0.6707
Epoch 20/20
753/753 ━━━━━━━━━━━━━━━━━━━━ 28s 37ms/step - accuracy: 0.7466 - loss: 0.6400 - val_accuracy: 0.7363 - val_loss: 0.6670

### Reflection:
The model did train faster, but it improved more slowly. This is humbling since I was so confident that my revisions would allow the model to converge faster. I guess I'll try switching back to my old model and just increasing the epochs.