# Sentiment Analysis Project
In this notebook, I'll document my process of creating a machine learning model that analyzes Twitter messages and predicts their sentiment.

In [1]:
import contractions
import matplotlib.pyplot as plt
import nltk
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from huggingface_hub import hf_hub_download
from gensim.models import KeyedVectors
from nltk.tokenize import TweetTokenizer
from tensorflow import keras
from tensorflow.keras import layers, regularizers, callbacks
from tensorflow.keras import callbacks
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dropout, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tqdm import tqdm

2025-10-31 18:49:05.343173: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1761950945.364819   22618 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1761950945.370908   22618 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1761950945.389220   22618 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761950945.389249   22618 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761950945.389251   22618 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761950945.389253   22618 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-10-31 18:49:05.395521: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/mnt/c/Users/Saniaa/PassionProject/nlp-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
print("GPUs available:", tf.config.list_physical_devices('GPU'))
print("Built with CUDA:", tf.test.is_built_with_cuda())
print("GPU available:", tf.config.list_physical_devices('GPU'))
print("cuDNN enabled:", tf.config.experimental.get_device_details(tf.config.list_physical_devices('GPU')[0]) if tf.config.list_physical_devices('GPU') else "No GPU found")

GPUs available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Built with CUDA: True
GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
cuDNN enabled: {'compute_capability': (8, 6), 'device_name': 'NVIDIA GeForce RTX 3050 Laptop GPU'}

In [3]:
data = pd.read_csv('Data/sentiment_data.csv')
data = data.dropna()
data.head()

   Unnamed: 0                                            Comment  Sentiment
0           0  lets forget apple pay required brand new iphon...          1
1           1  nz retailers don’t even contactless credit car...          0
2           2  forever acknowledge channel help lessons ideas...          2
3           3  whenever go place doesn’t take apple pay doesn...          0
4           4  apple pay convenient secure easy use used kore...          2

In [4]:
repo_id = "fse/glove-twitter-200"   # repo name on Hugging Face
file1 = "glove-twitter-200.model"
file2 = "glove-twitter-200.model.vectors.npy"
    
# Download both
model_file = hf_hub_download(repo_id=repo_id, filename=file1)
vectors_file = hf_hub_download(repo_id=repo_id, filename=file2)
    
print("Downloaded model:", model_file)
print("Downloaded vectors:", vectors_file)

glove_model = KeyedVectors.load(model_file)

Downloaded model: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model
Downloaded vectors: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model.vectors.npy

In [5]:
twtk = TweetTokenizer()

def make_token(sen):
    sen = contractions.fix(sen)
    return twtk.tokenize(sen)

data['Tokens'] = [make_token(sentence) for sentence in tqdm(data['Comment'])]
data.head()

100%|████████████████████████████████████████████████████████████████████████| 240928/240928 [00:12<00:00, 19054.90it/s]

,Unnamed: 0,Comment,Sentiment,Tokens
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us..."

In [6]:
#making dictionaries so that each word maps to it's vector

def make_token_vocab(sequences):
    token_vocab = set()  
    for seq in tqdm(sequences):
        for token in seq:
            if token in token_vocab:
                continue
            if token not in glove_model:
                continue
            token_vocab.add(token)
    return list(token_vocab)  
   
def make_token_indexes():
    indexes = []
    for index, token in tqdm(enumerate(token_vocab)):
        indexes.append(index + 1)
    return indexes

def make_vector_vocab():
    vector_vocab = []  
    for token in tqdm(token_vocab):
        vector_vocab.append(glove_model[token])
    return vector_vocab

token_vocab = make_token_vocab(data['Tokens'])
token_indexes = make_token_indexes()
vector_vocab = make_vector_vocab()

100%|███████████████████████████████████████████████████████████████████████| 240928/240928 [00:00<00:00, 376466.77it/s]
62681it [00:00, 2721226.86it/s]
100%|█████████████████████████████████████████████████████████████████████████| 62681/62681 [00:00<00:00, 688323.69it/s]

In [7]:
padding_token = '<PAD>'
padding_index = 0
padding_vector = np.zeros_like(vector_vocab[0])

token_vocab = [padding_token] + token_vocab
token_indexes = [padding_index] + token_indexes
vector_vocab = [padding_vector] + vector_vocab

token_index_dict = dict(zip(token_vocab, token_indexes))
token_vector_dict = dict(zip(token_vocab, vector_vocab))

In [8]:
#truncating message lengths
max_length = 100

data['Length'] = [len(tokens) for tokens in data['Tokens']]
data = data[data['Length'] < max_length]

In [9]:
def make_indices(seq):
    sequence = []
    for token in seq:
        if token not in glove_model:
            continue
        sequence.append(token_index_dict[token])
    return sequence

data['Indices'] = [make_indices(seq) for seq in tqdm(data['Tokens'])]

X_padded = pad_sequences(
    data['Indices'].tolist(), 
    maxlen=max_length, 
    padding='post',  
    truncating='post' 
)

embedding_matrix = np.array(vector_vocab)
data.head()

100%|███████████████████████████████████████████████████████████████████████| 240680/240680 [00:02<00:00, 100195.70it/s]

,Unnamed: 0,Comment,Sentiment,Tokens,Length,Indices
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,...",35,"[22994, 37923, 2903, 30640, 56366, 45757, 5478..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr...",20,"[58605, 5748, 26281, 25187, 50026, 38177, 3768..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,...",16,"[50469, 12367, 48328, 3141, 60796, 29841, 2289..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ...",58,"[44676, 30999, 3369, 58207, 25187, 1996, 30640..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us...",14,"[30640, 56366, 61859, 44364, 38633, 37407, 331..."

In [10]:
X = X_padded
y = data['Sentiment'].values

# Split into 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

# Convert labels to tf.int32
y_train = tf.cast(y_train, tf.int32)
y_test = tf.cast(y_test, tf.int32)

I0000 00:00:1761950996.997386   22618 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1765 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

### Learning Rate:
I increased the learning rate from 0.0001 to 0.001 because the training was taking way too long.

### Dropout:
Dropouts are used to improve generalization by randomly dropping neurons. This is so the model doesn't rely on a single dominating neuron and overfit. Each neuron captures a very specific pattern, so the model needs to learn patterns across many neurons.

### Kernel Regularizer:
The kernel regularizer controls the model's weights. Penalizing large weight values encourages the model to keep the weights smaller and simpler. If a weight gets too big, the model might solely rely on it instead of generalizing across various neurons.

In [18]:

def make_model():
    model = keras.Sequential()
    model.add(layers.Embedding(
        input_dim = len(token_vocab),
        output_dim = 200,
        weights = [embedding_matrix],  
        trainable = True,             
        mask_zero = True
    ))
    model.add(layers.LSTM(
        128, 
        kernel_regularizer=regularizers.l2(0.0001), 
        use_cudnn=False,
        dropout=0.2
    ))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(3, activation = 'softmax'))
    return model

model = make_model()

model.compile(
    optimizer = keras.optimizers.Adam(learning_rate=0.001),
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │    12,536,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,536,400 (47.82 MB)

 Trainable params: 12,536,400 (47.82 MB)

 Non-trainable params: 0 (0.00 B)

None

In [19]:
model_history = model.fit(
    X_train, y_train,
    batch_size = 128,
    epochs = 5,
    verbose = 1,
    validation_data = (X_test, y_test),
)

Epoch 1/5
1505/1505 ━━━━━━━━━━━━━━━━━━━━ 161s 104ms/step - accuracy: 0.7675 - loss: 0.6100 - val_accuracy: 0.8350 - val_loss: 0.4705
Epoch 2/5
1505/1505 ━━━━━━━━━━━━━━━━━━━━ 153s 102ms/step - accuracy: 0.8503 - loss: 0.4352 - val_accuracy: 0.8522 - val_loss: 0.4299
Epoch 3/5
1505/1505 ━━━━━━━━━━━━━━━━━━━━ 154s 102ms/step - accuracy: 0.8755 - loss: 0.3738 - val_accuracy: 0.8613 - val_loss: 0.4263
Epoch 4/5
1505/1505 ━━━━━━━━━━━━━━━━━━━━ 152s 101ms/step - accuracy: 0.8956 - loss: 0.3226 - val_accuracy: 0.8629 - val_loss: 0.4284
Epoch 5/5
1505/1505 ━━━━━━━━━━━━━━━━━━━━ 153s 102ms/step - accuracy: 0.9102 - loss: 0.2828 - val_accuracy: 0.8605 - val_loss: 0.4531

### Reflection:
Finally, we're getting somewhere! The overall accuracy has improved even more, and I've successfully reduced epochs. Still, the model is definitely overfitting. I think adding more dropout should encourage more generalization and hopefully increase validation accuracy.