# Sentiment Analysis Project
In this notebook, I'll document my process of creating a machine learning model that analyzes Twitter messages and predicts their sentiment.

In [1]:
import contractions
import nltk
import numpy as np
import pandas as pd
import tensorflow as tf
import torch

from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from huggingface_hub import hf_hub_download
from gensim.models import KeyedVectors
from nltk.tokenize import TweetTokenizer
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import Embedding, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tqdm import tqdm

2025-10-31 12:32:17.014004: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1761928337.050531    8551 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1761928337.060894    8551 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1761928337.094941    8551 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761928337.094981    8551 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761928337.094984    8551 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761928337.094986    8551 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-10-31 12:32:17.104842: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/mnt/c/Users/Saniaa/PassionProject/nlp-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data = pd.read_csv('Data/sentiment_data.csv')
data = data.dropna()
data.head()

   Unnamed: 0                                            Comment  Sentiment
0           0  lets forget apple pay required brand new iphon...          1
1           1  nz retailers don’t even contactless credit car...          0
2           2  forever acknowledge channel help lessons ideas...          2
3           3  whenever go place doesn’t take apple pay doesn...          0
4           4  apple pay convenient secure easy use used kore...          2

In [3]:
repo_id = "fse/glove-twitter-200"   # repo name on Hugging Face
file1 = "glove-twitter-200.model"
file2 = "glove-twitter-200.model.vectors.npy"
    
# Download both
model_file = hf_hub_download(repo_id=repo_id, filename=file1)
vectors_file = hf_hub_download(repo_id=repo_id, filename=file2)
    
print("Downloaded model:", model_file)
print("Downloaded vectors:", vectors_file)

glove_model = KeyedVectors.load(model_file)

Downloaded model: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model
Downloaded vectors: /home/saniaa/.cache/huggingface/hub/models--fse--glove-twitter-200/snapshots/72f480c107aaa58b9474ddaf45d13db2e34fa166/glove-twitter-200.model.vectors.npy

In [4]:
twtk = TweetTokenizer()

def make_token(sen):
    sen = contractions.fix(sen)
    return twtk.tokenize(sen)

data['Tokens'] = [make_token(sentence) for sentence in tqdm(data['Comment'])]
data.head()

100%|████████████████████████████████████████████████████████████████████████| 240928/240928 [00:13<00:00, 17760.33it/s]

,Unnamed: 0,Comment,Sentiment,Tokens
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us..."

In [5]:
#making dictionaries so that each word maps to it's vector

def make_token_vocab(sequences):
    token_vocab = set()  
    for seq in tqdm(sequences):
        for token in seq:
            if token in token_vocab:
                continue
            if token not in glove_model:
                continue
            token_vocab.add(token)
    return list(token_vocab)  
   
def make_token_indexes():
    indexes = []
    for index, token in tqdm(enumerate(token_vocab)):
        indexes.append(index + 1)
    return indexes

def make_vector_vocab():
    vector_vocab = []  
    for token in tqdm(token_vocab):
        vector_vocab.append(glove_model[token])
    return vector_vocab

token_vocab = make_token_vocab(data['Tokens'])
token_indexes = make_token_indexes()
vector_vocab = make_vector_vocab()

100%|███████████████████████████████████████████████████████████████████████| 240928/240928 [00:00<00:00, 369209.76it/s]
62681it [00:00, 3084704.19it/s]
100%|█████████████████████████████████████████████████████████████████████████| 62681/62681 [00:00<00:00, 700540.84it/s]

In [6]:
padding_token = '<PAD>'
padding_index = 0
padding_vector = np.zeros_like(vector_vocab[0])

token_vocab = [padding_token] + token_vocab
token_indexes = [padding_index] + token_indexes
vector_vocab = [padding_vector] + vector_vocab

token_index_dict = dict(zip(token_vocab, token_indexes))
token_vector_dict = dict(zip(token_vocab, vector_vocab))

In [7]:
#truncating message lengths
max_length = 100

data['Length'] = [len(tokens) for tokens in data['Tokens']]
data = data[data['Length'] < max_length]

In [8]:
def make_indices(seq):
    sequence = []
    for token in seq:
        if token not in glove_model:
            continue
        sequence.append(token_index_dict[token])
    return sequence

data['Indices'] = [make_indices(seq) for seq in tqdm(data['Tokens'])]

X_padded = pad_sequences(
    data['Indices'].tolist(), 
    maxlen=max_length, 
    padding='post',  
    truncating='post' 
)

embedding_matrix = np.array(vector_vocab)
data.head()

100%|███████████████████████████████████████████████████████████████████████| 240680/240680 [00:02<00:00, 101675.90it/s]

,Unnamed: 0,Comment,Sentiment,Tokens,Length,Indices
0,0,lets forget apple pay required brand new iphon...,1,"[let, us, forget, apple, pay, required, brand,...",35,"[50430, 56162, 18450, 45094, 38042, 2774, 4561..."
1,1,nz retailers don’t even contactless credit car...,0,"[nz, retailers, do, not, even, contactless, cr...",20,"[58971, 49715, 9319, 28700, 57128, 53360, 5513..."
2,2,forever acknowledge channel help lessons ideas...,2,"[forever, acknowledge, channel, help, lessons,...",16,"[15916, 17334, 27401, 38447, 55075, 24056, 297..."
3,3,whenever go place doesn’t take apple pay doesn...,0,"[whenever, go, place, does, not, take, apple, ...",58,"[57256, 21268, 21805, 18279, 28700, 15289, 450..."
4,4,apple pay convenient secure easy use used kore...,2,"[apple, pay, convenient, secure, easy, use, us...",14,"[45094, 38042, 44045, 14449, 21932, 13742, 778..."

In [9]:
X = X_padded
y = data['Sentiment'].values

# Split into 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

# Convert labels to tf.int32
y_train = tf.cast(y_train, tf.int32)
y_test = tf.cast(y_test, tf.int32)

I0000 00:00:1761928478.418535    8551 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1765 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

In [10]:
def make_model():
    model = keras.Sequential()
    model.add(layers.Embedding(
        input_dim = len(token_vocab),
        output_dim = 200,
        weights = [embedding_matrix],  
        trainable = False,             
        mask_zero = True
    ))
    model.add(layers.LSTM(32, use_cudnn=False))
    model.add(layers.Dense(3, activation = 'softmax'))
    return model

model = make_model()

model.compile(
    optimizer = keras.optimizers.Adam(learning_rate=0.0001),
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │    12,536,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,536,400 (47.82 MB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 12,536,400 (47.82 MB)

None

### Epochs
increased from 20 to 50

In [12]:
model_history = model.fit(
    X_train, y_train,
    batch_size = 256,
    epochs = 50,
    verbose = 1,
    validation_data = (X_test, y_test),
)

Epoch 1/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 66s 88ms/step - accuracy: 0.7876 - loss: 0.5407 - val_accuracy: 0.7722 - val_loss: 0.5796
Epoch 2/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 67s 89ms/step - accuracy: 0.7897 - loss: 0.5375 - val_accuracy: 0.7740 - val_loss: 0.5755
Epoch 3/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 68s 91ms/step - accuracy: 0.7912 - loss: 0.5341 - val_accuracy: 0.7744 - val_loss: 0.5742
Epoch 4/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 66s 88ms/step - accuracy: 0.7922 - loss: 0.5313 - val_accuracy: 0.7765 - val_loss: 0.5719
Epoch 5/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 62s 83ms/step - accuracy: 0.7944 - loss: 0.5281 - val_accuracy: 0.7769 - val_loss: 0.5695
Epoch 6/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 60s 80ms/step - accuracy: 0.7953 - loss: 0.5255 - val_accuracy: 0.7784 - val_loss: 0.5679
Epoch 7/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 66s 87ms/step - accuracy: 0.7967 - loss: 0.5229 - val_accuracy: 0.7799 - val_loss: 0.5653
Epoch 8/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 68s 90ms/step - accuracy: 0.7982 - loss: 0.5198 - val_accuracy: 0.7801 - val_loss: 0.5631
Epoch 9/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 63s 83ms/step - accuracy: 0.7993 - loss: 0.5176 - val_accuracy: 0.7816 - val_loss: 0.5628
Epoch 10/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 59s 78ms/step - accuracy: 0.8004 - loss: 0.5148 - val_accuracy: 0.7819 - val_loss: 0.5606
Epoch 11/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 64s 85ms/step - accuracy: 0.8019 - loss: 0.5122 - val_accuracy: 0.7838 - val_loss: 0.5589
Epoch 12/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 61s 81ms/step - accuracy: 0.8032 - loss: 0.5101 - val_accuracy: 0.7842 - val_loss: 0.5572
Epoch 13/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 63s 83ms/step - accuracy: 0.8039 - loss: 0.5076 - val_accuracy: 0.7853 - val_loss: 0.5556
Epoch 14/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 59s 79ms/step - accuracy: 0.8054 - loss: 0.5057 - val_accuracy: 0.7866 - val_loss: 0.5540
Epoch 15/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 64s 85ms/step - accuracy: 0.8065 - loss: 0.5031 - val_accuracy: 0.7841 - val_loss: 0.5566
Epoch 16/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 65s 87ms/step - accuracy: 0.8074 - loss: 0.5012 - val_accuracy: 0.7860 - val_loss: 0.5517
Epoch 17/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 64s 84ms/step - accuracy: 0.8086 - loss: 0.4990 - val_accuracy: 0.7877 - val_loss: 0.5496
Epoch 18/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 64s 84ms/step - accuracy: 0.8094 - loss: 0.4967 - val_accuracy: 0.7874 - val_loss: 0.5488
Epoch 19/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 62s 82ms/step - accuracy: 0.8103 - loss: 0.4947 - val_accuracy: 0.7876 - val_loss: 0.5492
Epoch 20/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 63s 84ms/step - accuracy: 0.8114 - loss: 0.4927 - val_accuracy: 0.7894 - val_loss: 0.5464
Epoch 21/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 63s 83ms/step - accuracy: 0.8127 - loss: 0.4908 - val_accuracy: 0.7903 - val_loss: 0.5455
Epoch 22/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 65s 86ms/step - accuracy: 0.8133 - loss: 0.4890 - val_accuracy: 0.7904 - val_loss: 0.5440
Epoch 23/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 65s 86ms/step - accuracy: 0.8141 - loss: 0.4871 - val_accuracy: 0.7920 - val_loss: 0.5427
Epoch 24/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 67s 89ms/step - accuracy: 0.8148 - loss: 0.4854 - val_accuracy: 0.7923 - val_loss: 0.5416
Epoch 25/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 63s 84ms/step - accuracy: 0.8154 - loss: 0.4835 - val_accuracy: 0.7925 - val_loss: 0.5407
Epoch 26/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 64s 85ms/step - accuracy: 0.8161 - loss: 0.4819 - val_accuracy: 0.7929 - val_loss: 0.5411
Epoch 27/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 62s 83ms/step - accuracy: 0.8174 - loss: 0.4803 - val_accuracy: 0.7935 - val_loss: 0.5390
Epoch 28/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 65s 86ms/step - accuracy: 0.8181 - loss: 0.4787 - val_accuracy: 0.7925 - val_loss: 0.5399
Epoch 29/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 68s 90ms/step - accuracy: 0.8187 - loss: 0.4770 - val_accuracy: 0.7938 - val_loss: 0.5388
Epoch 30/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 65s 86ms/step - accuracy: 0.8197 - loss: 0.4752 - val_accuracy: 0.7952 - val_loss: 0.5370
Epoch 31/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 67s 88ms/step - accuracy: 0.8198 - loss: 0.4738 - val_accuracy: 0.7951 - val_loss: 0.5368
Epoch 32/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 66s 87ms/step - accuracy: 0.8205 - loss: 0.4727 - val_accuracy: 0.7955 - val_loss: 0.5364
Epoch 33/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 67s 89ms/step - accuracy: 0.8214 - loss: 0.4705 - val_accuracy: 0.7957 - val_loss: 0.5361
Epoch 34/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 80s 107ms/step - accuracy: 0.8218 - loss: 0.4691 - val_accuracy: 0.7964 - val_loss: 0.5340
Epoch 35/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 67s 88ms/step - accuracy: 0.8235 - loss: 0.4675 - val_accuracy: 0.7974 - val_loss: 0.5331
Epoch 36/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 65s 87ms/step - accuracy: 0.8231 - loss: 0.4665 - val_accuracy: 0.7969 - val_loss: 0.5346
Epoch 37/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 65s 86ms/step - accuracy: 0.8237 - loss: 0.4650 - val_accuracy: 0.7983 - val_loss: 0.5330
Epoch 38/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 66s 87ms/step - accuracy: 0.8246 - loss: 0.4637 - val_accuracy: 0.7979 - val_loss: 0.5320
Epoch 39/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 66s 87ms/step - accuracy: 0.8254 - loss: 0.4624 - val_accuracy: 0.7975 - val_loss: 0.5347
Epoch 40/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 75s 100ms/step - accuracy: 0.8254 - loss: 0.4610 - val_accuracy: 0.7991 - val_loss: 0.5312
Epoch 41/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 71s 94ms/step - accuracy: 0.8263 - loss: 0.4596 - val_accuracy: 0.7991 - val_loss: 0.5303
Epoch 42/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 71s 95ms/step - accuracy: 0.8268 - loss: 0.4580 - val_accuracy: 0.8001 - val_loss: 0.5291
Epoch 43/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 72s 96ms/step - accuracy: 0.8272 - loss: 0.4570 - val_accuracy: 0.7997 - val_loss: 0.5284
Epoch 44/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 72s 96ms/step - accuracy: 0.8279 - loss: 0.4556 - val_accuracy: 0.8006 - val_loss: 0.5274
Epoch 45/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 72s 95ms/step - accuracy: 0.8285 - loss: 0.4544 - val_accuracy: 0.8010 - val_loss: 0.5283
Epoch 46/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 71s 94ms/step - accuracy: 0.8288 - loss: 0.4531 - val_accuracy: 0.8015 - val_loss: 0.5275
Epoch 47/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 72s 95ms/step - accuracy: 0.8298 - loss: 0.4519 - val_accuracy: 0.8015 - val_loss: 0.5268
Epoch 48/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 71s 94ms/step - accuracy: 0.8293 - loss: 0.4510 - val_accuracy: 0.8019 - val_loss: 0.5268
Epoch 49/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 72s 96ms/step - accuracy: 0.8305 - loss: 0.4496 - val_accuracy: 0.8001 - val_loss: 0.5288
Epoch 50/50
753/753 ━━━━━━━━━━━━━━━━━━━━ 70s 93ms/step - accuracy: 0.8312 - loss: 0.4483 - val_accuracy: 0.8016 - val_loss: 0.5273

### Reflection:
The model did a lot better, but it's still not as good as it can be. There has to be a better way to train without